// Generated by CoffeeScript 1.10.0
var App, Link, Page1, Page2, React, ReactDOM, Route, Router, ref;

React = require('react');

ReactDOM = require('react-dom');

ref = require('react-router'), Router = ref.Router, Route = ref.Route, Link = ref.Link;

App = React.createClass({displayName: "App",
  render: function() {
    return React.createElement("div", null, React.createElement("h1", null, "App"), React.createElement("ul", null, React.createElement("li", null, React.createElement(Link, {
      "to": "/page1"
    }, "Page 1")), React.createElement("li", null, React.createElement(Link, {
      "to": "/page2"
    }, "Page 2"))), this.props.children);
  }
});

Page1 = React.createClass({displayName: "Page1",
  render: function() {
    return React.createElement("h1", null, "Hello World Page1");
  }
});

Page2 = React.createClass({displayName: "Page2",
  render: function() {
    return React.createElement("h1", null, "Hello World Page2");
  }
});

ReactDOM.render(React.createElement(Router, null, React.createElement(Route, {
  "path": "/",
  "component": App
}, React.createElement(Route, {
  "path": "page1",
  "component": Page1
}), React.createElement(Route, {
  "path": "page2",
  "component": Page2
}))), document.getElementById('app'));
